/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.FrontEnd.FrontendPrincipal;

/**
 *
 * @author Kenny
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        this.setTitle("Libreria de juegos");
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PanelContenedor = new javax.swing.JPanel();
        BotonMemoria = new javax.swing.JButton();
        LabelTitulo = new javax.swing.JLabel();
        BotonHunting = new javax.swing.JButton();
        BotonReportes = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelContenedor.setBackground(new java.awt.Color(102, 102, 255));
        PanelContenedor.setForeground(new java.awt.Color(255, 255, 255));
        PanelContenedor.setLayout(new java.awt.GridBagLayout());

        BotonMemoria.setBackground(new java.awt.Color(153, 51, 255));
        BotonMemoria.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        BotonMemoria.setForeground(new java.awt.Color(0, 0, 0));
        BotonMemoria.setText("MEMORIA");
        BotonMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMemoriaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 147;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 372, 0, 0);
        PanelContenedor.add(BotonMemoria, gridBagConstraints);

        LabelTitulo.setBackground(new java.awt.Color(102, 255, 204));
        LabelTitulo.setFont(new java.awt.Font("Serif", 3, 48)); // NOI18N
        LabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        LabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitulo.setText("LIBRERIA DE JUEGOS ");
        LabelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 505;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        PanelContenedor.add(LabelTitulo, gridBagConstraints);

        BotonHunting.setBackground(new java.awt.Color(255, 102, 102));
        BotonHunting.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        BotonHunting.setForeground(new java.awt.Color(0, 0, 0));
        BotonHunting.setText("HUNTING");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 163;
        gridBagConstraints.ipady = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 372, 0, 0);
        PanelContenedor.add(BotonHunting, gridBagConstraints);

        BotonReportes.setBackground(new java.awt.Color(255, 0, 51));
        BotonReportes.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        BotonReportes.setForeground(new java.awt.Color(0, 0, 0));
        BotonReportes.setText("REPORTES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 159;
        gridBagConstraints.ipady = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 372, 0, 0);
        PanelContenedor.add(BotonReportes, gridBagConstraints);

        BotonSalir.setBackground(new java.awt.Color(255, 255, 51));
        BotonSalir.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        BotonSalir.setForeground(new java.awt.Color(0, 0, 0));
        BotonSalir.setText("SALIR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 197;
        gridBagConstraints.ipady = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 372, 91, 0);
        PanelContenedor.add(BotonSalir, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMemoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMemoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonHunting;
    private javax.swing.JButton BotonMemoria;
    private javax.swing.JButton BotonReportes;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPanel PanelContenedor;
    // End of variables declaration//GEN-END:variables
}
